### ISSUE TITLE
Front End Starter: Create a basic Login and Register page

### ISSUE THREAD

**Issue by cscaff** [Sckaff/UForum#10]
**Instructions**
- Create a simple background that follows the signature UF color scheme (orange, blue)
- Create input text boxes where a user can input their user name and password
- Give the option to register as well where options are extended to a user such that they must type in their UF email to verify that they are a student and their password as well as a password verification. 

**Related Stories**
- As a user, I want a simple way to register and then access my personal account where my forum data such as my post history and activity are stored.
- As a user, I want a secure account that can only be accessed by me through a unique password.

**Comment by bnielsen1** [comment]
Completed in rework
