### ISSUE TITLE
(Backend) Create comment system for posts

### ISSUE THREAD

**Issue by bnielsen1** [Sckaff/UForum#22]
Make a new comment object that has a foreign key to a post object. Comments should have the following functions attached to them so the frontend can make proper interactions.
- CreateComment() [create a comment from a postid and a text body. Should auto-fill user from token and requires login]
- DeleteComment() [delete a comment from comment id. requires login]
- EditComment() [edit a comment from comment id. requires login]

**Comment by sckaff** [comment]
Implemented.
