### ISSUE TITLE
(Backend) Implement post rating feature

### ISSUE THREAD

**Issue by bnielsen1** [Sckaff/UForum#25]
Create a similar system to youtube likes or any other platform
- Posts have an array of usernames called likes and array called dislikes and three functions. There should also be an unsigned int that stores likes.length - dislikes.length
- LikePost() [requires login and adds the user to the the like array and removes them from the dislike array (check if missing/duplicate)
- DislikePost() [opposite of like post]
- ClearPostLikes() [requires login and removes a user from both arrays to unvote]
- This is my proposed system that should work well with the frontend but if you guys have a better idea lmk

**Comment by sckaff** [comment]
Implemented.
