### ISSUE TITLE
Admin functions and admin users

### ISSUE THREAD

**Issue by bnielsen1** [Sckaff/UForum#29]
Create a new group of functions (similar to those that require a login) but check to see if their username is on some sort of admin list before allowing them to make these calls
- CreateCategory() DeleteCategory() EditCategory() [self explanatory]
- AdminDeletePost() [allows a user to delete any post not just their own]
- AdminDeleteComment() [allows a user to delete any comment once comments are implemented]
- DeleteUser()

**Comment by sckaff** [comment]
We did all of this besides DeleteUser() since we don't deem fit.
