### ISSUE TITLE
Create User Registration and Email Verification database system

### ISSUE THREAD

**Issue by sckaff** [Sckaff/UForum#7]
Related Stories

- As a user, I want a simple way to create an account, and be sure that every account is from a UF student.
- As a user, I want to be able to update my user profile, such as my password or profile picture.

Create a database for logging in with GORM that also requests email verification and stores the user's basic information in the database. 
- Encrypt passwords if possible, but not necessary for Sprint 1.
- Same for accepting only emails with @ufl.edu
- Rely on libraries

Include:
- Nickname
- First and Last name
- UF email
- Date of creation (Stored on the database)
- Profile picture (Default is a Gator)
- Phone Number(optional)

**Comment by bnielsen1** [comment]
Completed in rework but email verification system will come later or not at all depending on difficulty
